### ISSUE TITLE
[CONFERENCE] PYDATA GLOBAL 2022

### ISSUE THREAD

**Issue by crazy4pi314** [kjaymiller/Python-Community-News#107]
### Conference Name

PYDATA GLOBAL

### URL

https://pydata.org/global2022/

### Conference Dates

01 DEC - 03 DEC 2022

### Conference Type

online

### CFP URL

https://pydata.org/global2022/present/

### CFP End Date

12-09-2022

### Conference Description

WHAT TO EXPECT
The PyData Global Online Conference is where users, contributors, and newcomers can share experiences to learn from one another and grow together. PyData provides a virtual forum for the international community of users and developers of data analysis tools to share ideas and learn from each other. The global PyData network promotes discussion of best practices, new approaches, and emerging technologies for data management, processing, analytics, and visualization.

This three-day online event consists of talks, tutorials, and discussions to bring attendees the latest project features along with cutting edge use cases.

The time span of the conference stretches beyond any single time zone, reflecting the global nature of our community. To accommodate our attendees, each session will be recorded and made available to attendees the following day. Following the Conference, all recordings will be posted to the PyData YouTube channel.

**Comment by kjaymiller** [comment]
Thank you for adding this event! \n We'll happily consider it for the next episode. \n\n The Issue autocloses but we'll be reviewing it at https://github.com/users/kjaymiller/projects/4/views/3
