### ISSUE TITLE
Python Community News 23 Sept 2022

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#119]
### Use this checklist to walk through all the steps you'll need to complete for each episode

- [x] Download the Audio/Video from StreamYard
- [ ] Share the YouTube link with folks on social media
- [x] Break the video into chapters
- [x] Update Timestamps in Shownotes Post
- [x] Publish podcast episode
- [ ] Add Github link/podcast url/and YouTube link to content

### Episode Date

2022-09-23

### YouTube

Pz03Q8wuq8M

### Podcast

6651f036

### Issues

#115, #116, #117, #118, #121, #122

### CFPS
#25 

### Newsletter Publish

2022-09-26T08:00-08:00

**Comment by jonafato** [comment]
Edited to link issues and remove item incorrectly categorized as a conference.

**Comment by kjaymiller** [comment]
I meant to message you on this as the publish script kept breaking due to not having a CFPs or conferences. I manually entered them to get running and updated the content after. There will need to be issues filed to ignore empty fields.
