### ISSUE TITLE
[CONFERENCE] Python Brasil 2022

### ISSUE THREAD

**Issue by dawnwages** [kjaymiller/Python-Community-News#123]
### Conference Name

Python Brasil 2022

### URL

Pycon Brasil 2022

### Conference Dates

17-10-2022 - 23-10-2022

### Conference Type

both

### Conference Location

Manaus, Brasil

### Conference Description

Python Brasil 2022 is the largest conference on Python programming language in Brazil and Latin America.

There will be 7 days of immersion where participants can contribute to free software projects, participate in training and acquire new knowledge with renowned developers of the community. The program is organized as follows: Tutorials (15.10 and 16.10), Lectures and Keynotes (17.10 to 22.10) and Sprints (23.10).

The 2022 edition is being organized by the Python community of Manaus / AM (PyNorte) with the support of APyB (Python Brazil Association).

**Comment by kjaymiller** [comment]
Thank you for adding this event! \n We'll happily consider it for the next episode. \n\n The Issue autocloses but we'll be reviewing it at https://github.com/users/kjaymiller/projects/4/views/3
