### ISSUE TITLE
Securing Open Source Software Act

### ISSUE THREAD

**Issue by jonafato** [kjaymiller/Python-Community-News#125]
### URL

https://www.congress.gov/bill/117th-congress/senate-bill/4913/text

### When was this post released

20220921

### Summary

US Senators have introduced the Open Source Software Act, a bill to strengthen the security of open source software used by the United States Government. The bill instructs the Director of the Cybersecurity and Infrastructure Security Agency to publish a framework for evaluating the security of critical open source components and to assess open source components used by federal agencies using this framework every two years. The full text of the bill can be found at [S. 4913 on congress.gov](https://www.congress.gov/bill/117th-congress/senate-bill/4913/text), and you can find a page-by-page summary as a [Twitter thread by Dustin Ingram](https://twitter.com/di_codes/status/1574447938054410246).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kjaymiller** [comment]
https://twitter.com/di_codes/status/1574447938054410246
