### ISSUE TITLE
As a community should we be helping build an ecosystem of Central Bank Digital Currencies (CBDC's)

### ISSUE THREAD

**Issue by Back2Basics** [kjaymiller/Python-Community-News#133]
### URL

https://pages.awscloud.com/GLOBAL-public-DL-cbdc-whitepapers-reg.html

### Summary

The programming communities are going to be asked to get involved with nationalizing cryptocurrencies.  Should we push back on programmable money at the national level as a community?
Topic points:
* What happens when a central authority has this type of power with programmable money?  (incentive programs, deterrent programs)
* Differences between decentralized cryptocurrencies (bitcoin, etherium) and CBDC's

links: 
* https://www.whitehouse.gov/briefing-room/statements-releases/2022/09/16/fact-sheet-white-house-releases-first-ever-comprehensive-framework-for-responsible-development-of-digital-assets/
* https://www.csis.org/blogs/new-perspectives-asia/chinas-progress-towards-central-bank-digital-currency

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kjaymiller** [comment]
Hey Thanks for Submitting a topic! We've been workin to move to a new repo... Can you do me a favor and copy/paste this into https://github.com/python-community-news/topics/issues/new/choose
