### ISSUE TITLE
Set the title to [CONFERENCE] <Conference Name> and the Year

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#23]
Remove the date requirements for the conference date in the title

**Comment by Rashmibss** [comment]
Need a little more context on where to make this change. Do I have to remove the date from the episdoe_template

**Comment by kjaymiller** [comment]
Happy to help with this - I've renamed the issue to the correct format that we're going with. You would need to replace it in the title of the [issue template](https://github.com/kjaymiller/Python-Community-News/blob/main/.github/ISSUE_TEMPLATE/Add%20Conference.yaml).

**Comment by kjaymiller** [comment]
The fix looks like we need to just add the year.
![CleanShot 2022-08-31 at 00 14 08@2x](https://user-images.githubusercontent.com/8632637/187616504-a200ddee-48ae-466b-ae45-b98e87b27a89.png)
