### ISSUE TITLE
Meta: Conference Issue Management

### ISSUE THREAD

**Issue by jonafato** [kjaymiller/Python-Community-News#35]
We're quickly racking up a bunch of conference announcement issues, which will all be compressed into a small segment of the show and may be redundant (e.g. we mentioned DjangoCon US last week). I wonder if we can make this a bit more streamlined with two changes:

1. Directing the efforts to track individual conferences toward https://github.com/python-organizers/conferences as an existing and well established location for sharing information about Python conferences
2. Creating some set of criteria we use to pull updates from that repository, largely so that we cover everything we want to without duplicating it too much. This could look something like:
    1. New conference and CFP announcements get added when they first appear in the repository
    2. CFPs get a second mention a week or two before the due date
    3. Ticket sales get a "last chance" mention a week or two before the event (or before sales close, if that is a thing)

This would have the added benefits of helping with a common resource that already exists and giving us the ability to automate announcements for our recurring segments.

**Comment by jonafato** [comment]
Relates to #29.

**Comment by kjaymiller** [comment]
> Directing the efforts to track individual conferences toward https://github.com/python-organizers/conferences as an existing and well established location for sharing information about Python conferences. 

1. I didn't know about this, but also 2022 only has 6 events which seems low. (Considering we have that many listed for the next 3 months). My guess is this sentence --> "If you are a conference organizer, we can give you direct access to the repository, but it is your responsibility to update your own event!"

> Creating some set of criteria we use to pull updates from that repository, largely so that we cover everything we want to without duplicating it too much. This could look something like:

I like this idea and totally support it. I think we can do that organically around the nature of conferences.
My idea wasn't to talk about all the conferences in the issues every episode just have them listed so that we can find them quickly. I quickly realized I should add us as assignees to it.
    - New conference and CFP announcements get added when they first appear in the repository - **I think only when the CFP is announced** If we missed the CFP I think we just mention it perhaps 1 week before (I know that isn't giving people much time for travel but if we're added it as an issue they will be able to view it in [this board](https://github.com/users/kjaymiller/projects/4/views/3)
    - CFPs get a second mention a week or two before the due date - **I like 1 week before**
    - Ticket sales get a "last chance" mention a week or two before the event (or before sales close, if that is a thing) - **1 week**

I do like the idea of giving back to a resource but I worry that our reliance on it will mean ultimately events get missed. Perhaps I can file some issues to make templates similar to what we currently have and work with the organizers to make the process more optimal.

**Comment by jonafato** [comment]
> I didn't know about this, but also 2022 only has 6 events which seems low. (Considering we have that many listed for the next 3 months). My guess is this sentence --> "If you are a conference organizer, we can give you direct access to the repository, but it is your responsibility to update your own event!"

I (along with many other conference organizers) have access to this repository, and people have definitely updated others' events in the past. I don't think anyone will object to us bringing some activity back there, and if we're tracking a bunch of events regardless, we may as well contribute. For a long time, this was the most comprehensive list of Python conferences around, which helps the whole community.

**Comment by jonafato** [comment]
> I like 1 week before

I should have been more specific here. I said "one or two" but really meant "between one and two", because the newsletter and show won't sync up exactly with these due dates. In those edge cases, eight days is probably a more useful reminder than one day.

**Comment by kjaymiller** [comment]
There are a couple of things in this. Can we close this topic as discussed around the first topic and build some issues around the other points that can be added to the repo README perhaps?

**Comment by jonafato** [comment]
Yeah, I think we're all good here and have discussed everything we need to both here and out of band.
