### ISSUE TITLE
Reformat with Pre-Commit

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#57]
Over all looks good. Can you run the formatters via pre-commit and push the changes?

_Originally posted by @jonafato in https://github.com/kjaymiller/Python-Community-News/pull/48#pullrequestreview-1092764320_

**Comment by jonafato** [comment]
This was feedback for that pull request, not a general issue. I originally performed this step when first adding pre-commit to make sure everything was up to date, and the idea is that future changes will be blocked from merging without proper formatting (which I noted in #52 but will add as a dedicated issue).
