### ISSUE TITLE
[FEATURE] Swap `tailwindcss` from NPM to `pytailwindcss` to remove the need for `package.json` and `package-lock.json`

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#60]
Currently the build steps for `web` are to run `tailwindcss` to compile tailwind from the template.

There is a package [`pytailwindcss`](https://pypi.org/project/pytailwindcss/) that can compile tailwind via python.

**Comment by jonafato** [comment]
I wouldn't oppose this change, the main benefit being ease of development, especially for new contributors. Tailwind's own announcement about the CLI says 

> If on the other hand you’re working on a project where you don’t otherwise need Node.js or npm, the standalone build can be a great choice. If Tailwind was the only reason you had a package.json file, this is probably going to feel like a nicer solution.

Which seems like it fits our use case pretty well.

(Note that this is not _actually_ Python, it's just a Python wrapper that helps install the CLI binary. This doesn't change its usefulness, just pointing out that it isn't a Tailwind reimplementation or anything like that.)

**Comment by kjaymiller** [comment]
Resolved in #90
