### ISSUE TITLE
Add `[DISCUSSION]` Github Issues template

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#79]
Create a `DISCUSISON` GitHub issues template

This should preface the issue title `[DISCUSSION]` and set the label `discussion` and cc: `@kjaymiller, @jonafato`

**Comment by jonafato** [comment]
@kjaymiller Is there much value in the prefix if we have a label?

**Comment by kjaymiller** [comment]
Honestly I was using it for quick discovery but I am okay with not adding this
