### ISSUE TITLE
[CONFERENCE] <Python Científico Latino América 2022> 2022

### ISSUE THREAD

**Issue by DennyPerez18** [kjaymiller/Python-Community-News#92]
### Conference Name

Python Científico Latino América 2022

### URL

https://pythoncientifico.ar/

### Conference Dates

26th - 28th September, 2022

### Conference Type

in-person

### Conference Location

Ciudad de Salta, Argentina

### CFP URL

Finished

### CFP Dates

03-09-2022

### Conference Description

9th Latin American Scientific Python Conference

City of Salta, Argentina.

Share experiences on the use of scientific Python both academically and professionally, our goals are simple:

Promote science.
Promote the adoption of information technology as a tool for scientific study.
Promote the use of Python as the main computing tool in science.
Registration for the event is FREE
It is open to all interested public, you just have to REGISTER please.

https://pythoncientifico.ar/accounts/registration/

**Comment by kjaymiller** [comment]
Thank you for adding this event! \n We'll happily consider it for the next episode. \n\n The Issue autocloses but we'll be reviewing it at https://github.com/users/kjaymiller/projects/4/views/3
