### ISSUE TITLE
fast-math compiler options result in incorrect math results

### ISSUE THREAD

**Issue by crazy4pi314** [kjaymiller/Python-Community-News#93]
### URL

https://moyix.blogspot.com/2022/09/someones-been-messing-with-my-subnormals.html

### When was this post released

Sept 6th, 2022

### Summary

Fast math compilation options lead to incorrect floating point math results. When you use gcc to compile, you can use an option to ask it to drop precision to speed up the compilation, but when the shared library is loaded it also sets a CPU flag to use less numerically precise methods for speed. This flag should only be set during compilation, and not carry to the produced code. The linked blog post investigates packages on pip and found 2500 packages that exhibit the degraded numerical precision if complied fast.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonafato** [comment]
Thanks for contributing this story! I've reworded the text to match the style of other items a bit but included the original copy below:

> Fast compilation option -> Incorrect math?!
> 
>     Note this is technically broader than Python, but this blog post used packages from pip to demonstrate the vulnerability.
> 
> When you use gcc to compile, you can use an option to ask it to drop precision to speed up the compilation. Sounds reasonable, but what happens is that when the shared library is loaded when the package it also sets a CPU flag to use less numerically precise methods for speed. This should not happen as the flag should only be set during compilation, and not carry to the produced code. The blog post linked above investigates packages on pip and 2500 packages (some with more than 1 million downloads a month) can exhibit the degraded numerical precision if complied fast.
> 
> It's a fairly niche case, but if you compile packages from source, it's a fun edge case to avoid :)
