### ISSUE TITLE
OSS team working on improving scientific python workflows

### ISSUE THREAD

**Issue by crazy4pi314** [kjaymiller/Python-Community-News#94]
### URL

https://scientific-python.org/

### When was this post released

Not a specific post

### Summary

Scientific Python (a NumFOCUS project) is developing PEP like rules for scientific python packages called SCIENTIFIC PYTHON ECOSYSTEM COORDINATION (SPEC). SPECs provide operational guidelines for projects in the scientific Python ecosystem. The SPEC process is described in the [SPEC Purpose and Process](https://scientific-python.org/specs/purpose-and-process/), [SPEC Steering Committee](https://scientific-python.org/specs/steering-committee/), and [SPEC Core Projects](https://scientific-python.org/specs/core-projects/) documents. Community discussions take place on the [SPECs Discourse forum](https://discuss.scientific-python.org/c/specs/6).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kjaymiller** [comment]
Thank you for contributing this topic.

We opted to not cover this as a part of this show due to the older age of the creation. That said we will be adding Numfocus and Scientific Python to the list of resources to keep an eye on. We may also use this in a future longer more researched topic.
